name: "Configure Java and Gradle Wrapper"
description: "Download and configure the desired gradle wrapper"
inputs:
  os:
    description: 'OS'
    required: true
    default: 'ubuntu-latest'
  java-version:
    description: 'Java version'
    required: true
    default: '17'
  jdk-publisher:
    description: 'JDK Publisher'
    required: true
    default: 'corretto'
  gradle-version:
    description: 'Gradle version'
    required: true
    default: '7.6.1'

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3
    - name: Set Gradle Version
      shell: bash
      run: ./gradlew wrapper --gradle-version=${{ inputs.gradle-version }}
    - name: Verify Gradle Version Set
      shell: bash
      run: ./gradlew -v
    - uses: gradle/wrapper-validation-action@v1
    - name: Set up JDK ${{ inputs.java-version }}
      uses: actions/setup-java@v3
      with:
        java-version: ${{ inputs.java-version }}
        distribution: ${{ inputs.jdk-publisher }}         # List of supported jvms https://github.com/actions/setup-java
        server-id: github                                 # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }}            # location for the settings.xml file
        #cache: gradle - this causes problems on github build